project:
  type: website
  output-dir: docs

website:
  title: "Malariaverse Workshop"
  navbar:
    logo: "presentations/images/malariaverse.gif"
    left:
      - text: "Home"
        file: index.qmd
      - text: "Workshop materials"
        file: materials.qmd
      - text: "Coffee break activity"
        file: coffee.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

